PREP(buttonDeleteProfile);
PREP(buttonLoadProfile);
PREP(buttonRenameProfile);
PREP(buttonSaveProfile);
PREP(loadProfile);
PREP(onDisplayClose);
PREP(onDisplayOpen);
PREP(populateProfiles);
PREP(saveProfile);